### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mordag** [Mordag/android-sensors#1]
- [ ] Track heartbeat via finger touch (MotionEvent getPressure and calc messure the possible heartbeat)
- [ ] Proximity Sensor implementation to track if the device can correctly track a person in a certain distant
- [ ] Moving phone up/down to trigger events (sensor?)
- [ ] Send tracked data via bluetooth to another device (only calculated data)
